/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-29 05:27:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/aipage/SMT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/smt/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/inc/foot.jspf", Long.valueOf(1688016086248L));
    _jspx_dependants.put("/inc/top.jspf", Long.valueOf(1688002602643L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682573782632L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Editorial by HTML5 UP</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/assets/css/main.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- jquery 라이브러리 CDN방식으로 참조------------- -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("<!-- --------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Wrapper -->\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Main -->\r\n");
      out.write("		<div id=\"main\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Header -->\r\n");
      out.write("				<header id=\"header\">\r\n");
      out.write("					<a href=\"/\" class=\"logo\"><strong>Editorial</strong> by HTML5 UP</a>\r\n");
      out.write("\r\n");
      out.write("				</header>");
      out.write("\r\n");
      out.write("<!-- ckeditor 4 cdn--------------------------- -->\r\n");
      out.write("<script src=\"https://cdn.ckeditor.com/4.17.2/standard/ckeditor.js\"></script>\r\n");
      out.write("<!-- ----------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		 \r\n");
      out.write("		CKEDITOR.replace('bcontent',{\r\n");
      out.write("			removeButtons:'Image',\r\n");
      out.write("		    height: '500px'\r\n");
      out.write("		});\r\n");
      out.write("		 \r\n");
      out.write("		$('#bf').css('font-size', '15pt');\r\n");
      out.write("\r\n");
      out.write("		$('#bf').submit(function() {\r\n");
      out.write("			if (!$('#title').val()) {\r\n");
      out.write("				alert('제목을 입력하세요');\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			if (!CKEDITOR.instances.bcontent.getData()) {\r\n");
      out.write("				alert('내용을 입력하세요');\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			return true;\r\n");
      out.write("		})//submit----------------\r\n");
      out.write("\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Banner -->\r\n");
      out.write("<section id=\"banner\">\r\n");
      out.write("	<div class=\"content\" id=\"boardwrite\">\r\n");
      out.write("		<header style=\"text-align: center\">\r\n");
      out.write("			<h2 style=\"text-align:center; font-family:sans-serif\">게시판 글쓰기 페이지</h2>\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("		<!-- 내가 작성------------------------------------ -->\r\n");
      out.write("		<form name=\"bf\" id=\"bf\" action=\"write\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"width:10%; text-align:center\"><b>제목</b></td>\r\n");
      out.write("					<td style=\"width:80\">\r\n");
      out.write("					<input type=\"text\" name=\"title\" id=\"title\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align:center\"><b>작성자</b></td>\r\n");
      out.write("					<td>\r\n");
      out.write("					<input type=\"text\" name=\"idx\" id=\"idx\">\r\n");
      out.write("					<!-- 하민지 -->\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\">\r\n");
      out.write("					<textarea name=\"content\" id=\"bcontent\"></textarea>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align:center\"><b>첨부 파일</b></td>\r\n");
      out.write("					<td>\r\n");
      out.write("					<input type=\"file\" name=\"mfilename\" id=\"filename\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"actions\" style=\"text-align: center\">\r\n");
      out.write("				<li><button class=\"button special\"><span style=\"font-size:14pt; font-family:sans-serif\">등록</span></button></li>\r\n");
      out.write("				<li><a href=\"/board/list\" class=\"button\" style=\"font-family:sans-serif\"><span style=\"font-size:14pt; font-family:sans-serif\">취소</span></a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("		<!-- -------------------------------- -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<!-- Section -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar -->\r\n");
      out.write("<div id=\"sidebar\">\r\n");
      out.write("	<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Search -->\r\n");
      out.write("		<section id=\"search\" class=\"alt\">\r\n");
      out.write("			<form method=\"post\" action=\"#\">\r\n");
      out.write("				<input type=\"text\" name=\"query\" id=\"query\" placeholder=\"Search\" />\r\n");
      out.write("			</form>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Menu -->\r\n");
      out.write("		<nav id=\"menu\">\r\n");
      out.write("			<header class=\"major\">\r\n");
      out.write("				<h2>Menu</h2>\r\n");
      out.write("			</header>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"/\">Homepage</a></li>\r\n");
      out.write("				<li><a href=\"/board/list\">Board</a></li>\r\n");
      out.write("				<li><a href=\"#\">Elements</a>\r\n");
      out.write("				<li><span class=\"opener\">AI 상담</span>\r\n");
      out.write("					<ul>\r\n");
      out.write("\r\n");
      out.write("						<li><a href=\"chat.html\">실시간 ai 상담</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("		<footer id=\"footer\">\r\n");
      out.write("			<p class=\"copyright\">&copy; Untitled. All rights reserved. Demo Images: <a href=\"https://unsplash.com\">Unsplash</a>. Design: <a href=\"https://html5up.net\">HTML5 UP</a>.</p>\r\n");
      out.write("		</footer>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("<script src=\"/resources/assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/assets/js/skel.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/assets/js/util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/resources/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
