/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-07-01 00:08:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/aipage/SMT/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/smt/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/inc/foot.jspf", Long.valueOf(1688022240545L));
    _jspx_dependants.put("/inc/top.jspf", Long.valueOf(1688087844522L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682573782632L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>SMT</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/assets/css/main.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- jquery 라이브러리 CDN방식으로 참조------------- -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("	integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- --------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Wrapper -->\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Main -->\r\n");
      out.write("		<div id=\"main\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Header -->\r\n");
      out.write("				<header id=\"header\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"logo\"><strong>SMT</strong> Say Mbit\r\n");
      out.write("						Type</a>\r\n");
      out.write("					<ul class=\"actions\" style='text-align: right' id=\"login_join\">\r\n");
      out.write("						<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"button special\">login</a></li>\r\n");
      out.write("						<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/join\" class=\"button special\">join</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- form 양식 체크하는 js파일 들어갈 자리 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"box\" style=\"padding: 20px;\">\r\n");
      out.write("	<form id=\"join_form\" method=\"post\">\r\n");
      out.write("		<h2 style=\"color: #f56a6a; text-align: center;\">회원가입 - Signup</h2>\r\n");
      out.write("		<div id=\"userid_wrap\">\r\n");
      out.write("			<div style=\"color: #f56a6a; font-weight: bold;\">아이디</div>\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<input type=\"text\" name=\"userid\" id=\"userid\" placeholder=\"👤ID\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"userpwd_wrap\">\r\n");
      out.write("			<div style=\"color: #f56a6a; font-weight: bold;\">비밀번호</div>\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<input type=\"password\" name=\"userpwd\" id=\"userpwd\" placeholder=\"🔒Password\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"userpwd2_wrap\">\r\n");
      out.write("			<div style=\"color: #f56a6a; font-weight: bold;\">비밀번호 확인</div>\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<input type=\"password\" name=\"userpwd2\" id=\"userpwd2\" placeholder=\"🔒Re Password\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"name_wrap\" style=\"padding-top: 20px;\">\r\n");
      out.write("			<div style=\"color: #f56a6a; font-weight: bold;\">이름</div>\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"Name\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"bday_wrap\">\r\n");
      out.write("			<div style=\"color: #f56a6a; font-weight: bold;\">생년월일</div>\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<input type=\"date\" name=\"bday\" id=\"bday\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"hp_wrap\" style=\"width: 100%\">\r\n");
      out.write("			<div style=\"color: #f56a6a; font-weight: bold;\">연락처</div>\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<div style=\"width: 32%; float: left;\">\r\n");
      out.write("					<input type=\"text\" name=\"hp1\" id=\"hp1\" placeholder=\"HP1\" maxlength=\"3\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"width: 34%; float: left;\">\r\n");
      out.write("					<input type=\"text\" name=\"hp2\" id=\"hp2\" placeholder=\"HP2\" maxlength=\"4\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"width: 34%; float: right;\">\r\n");
      out.write("					<input type=\"text\" name=\"hp3\" id=\"hp3\" placeholder=\"HP3\" maxlength=\"4\"><br>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"nickname_wrap\" style=\"padding-top: 40px;\">\r\n");
      out.write("			<div style=\"color: #f56a6a; font-weight: bold;\">닉네임</div>\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<input type=\"text\" name=\"nick_name\" id=\"nick_name\" placeholder=\"Nick Name\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"mbti_wrap\">\r\n");
      out.write("			<div style=\"color: #f56a6a; font-weight: bold;\">MBTI</div>\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<select name=\"mbti_type\" id=\"mbti_type\" style=\"text-align: center;\">\r\n");
      out.write("					<option value=\"\">- MBTI유형을 선택해주세요. -</option>\r\n");
      out.write("					<option value=\"ENFP\">ENFP</option>\r\n");
      out.write("					<option value=\"ENFJ\">ENFJ</option>\r\n");
      out.write("					<option value=\"ENTP\">ENTP</option>\r\n");
      out.write("					<option value=\"ENTJ\">ENTJ</option>\r\n");
      out.write("					<option value=\"ESFP\">ESFP</option>\r\n");
      out.write("					<option value=\"ESFJ\">ESFJ</option>\r\n");
      out.write("					<option value=\"ESTP\">ESTP</option>\r\n");
      out.write("					<option value=\"ESTJ\">ESTJ</option>\r\n");
      out.write("					<option value=\"INFP\">INFP</option>\r\n");
      out.write("					<option value=\"INFJ\">INFJ</option>\r\n");
      out.write("					<option value=\"INTP\">INTP</option>\r\n");
      out.write("					<option value=\"INTJ\">INTJ</option>\r\n");
      out.write("					<option value=\"ISFP\">ISFP</option>\r\n");
      out.write("					<option value=\"ISFJ\">ISFJ</option>\r\n");
      out.write("					<option value=\"ISTP\">ISTP</option>\r\n");
      out.write("					<option value=\"ISTJ\">ISTJ</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"pimage_wrap\">\r\n");
      out.write("			<div style=\"color: #f56a6a; font-weight: bold;\">프로필 이미지</div>\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<input type=\"file\" name=\"pimage\" id=\"pimage\" accept=\".png, .jpg, .jpeg\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div style=\"padding-top: 30px;\">\r\n");
      out.write("			<button type=\"button\" id=\"join_button\" class=\"button special fit\">회원가입</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	//회원가입 버튼(회원가입 기능 작동)\r\n");
      out.write("	$(\"#join_button\").click(function(){\r\n");
      out.write("		alert('전송');\r\n");
      out.write("		$(\"#join_form\").attr(\"action\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/join\");\r\n");
      out.write("		$(\"#join_form\").submit();\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar -->\r\n");
      out.write("<div id=\"sidebar\">\r\n");
      out.write("	<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Search -->\r\n");
      out.write("		<section id=\"search\" class=\"alt\">\r\n");
      out.write("			<form method=\"post\" action=\"#\">\r\n");
      out.write("				<input type=\"text\" name=\"query\" id=\"query\" placeholder=\"Search\" />\r\n");
      out.write("			</form>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Menu -->\r\n");
      out.write("		<nav id=\"menu\">\r\n");
      out.write("			<header class=\"major\">\r\n");
      out.write("				<h2>Menu</h2>\r\n");
      out.write("			</header>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"/\">Homepage</a></li>\r\n");
      out.write("				<li><a href=\"/board/list\">Board</a></li>\r\n");
      out.write("				<li><a href=\"#\">Elements</a>\r\n");
      out.write("				<li><span class=\"opener\">AI 상담</span>\r\n");
      out.write("					<ul>\r\n");
      out.write("\r\n");
      out.write("						<li><a href=\"/chat/chat\"]\">실시간 ai 상담</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("		<footer id=\"footer\">\r\n");
      out.write("			<p class=\"copyright\">&copy; Untitled. All rights reserved. Demo Images: <a href=\"https://unsplash.com\">Unsplash</a>. Design: <a href=\"https://html5up.net\">HTML5 UP</a>.</p>\r\n");
      out.write("		</footer>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("<script src=\"/resources/assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/assets/js/skel.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/assets/js/util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/resources/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /inc/top.jspf(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("myctx");
      // /inc/top.jspf(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/inc/top.jspf(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
